version: "3.9"
   
services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    environment:
      SECRET_KEY: please_don't_push_me_to_github
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    container_name: seafight_cntnr
